{% set name = "ht" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6ad9ce607ebfa62c73a449a47923c737512b76577b3935d6d9b1f5b016924e4

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - fluids >=1.0.27
    - numpy >=1.5.0
    - python >=3.6
    - scipy >=0.9.0

test:
  imports:
    - ht

about:
  home: https://github.com/CalebBell/ht
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Heat transfer component of Chemical Engineering Design Library (ChEDL)
  description: |
    ht is open-source software for engineers and technicians working in the fields of chemical 
    or mechanical engineering. It includes modules for various heat transfer functions.

    The ht library depends on the SciPy library to provide numerical constants, interpolation, integration, 
    and numerical solving functionality. ht runs on all operating systems which support Python, is quick to install, 
    and is free of charge. ht is designed to be easy to use while still providing powerful functionality. 
    If you need to perform some heat transfer calculations, give ht a try.
  doc_url: https://ht.readthedocs.io/en/latest/
  dev_url: https://github.com/CalebBell/ht

extra:
  recipe-maintainers:
    - volpatto
    - CalebBell
